const GENRES = [
  "Action",
  "Adventure",
  "Anthology",
  "Art",
  "Autobiography",
  "Biography",
  "Business",
  "Chick Lit",
  "Children's",
  "Classic",
  "Comics",
  "Coming-of-Age",
  "Cookbook",
  "Crime",
  "Drama",
  "Dystopian",
  "Educational",
  "Essay",
  "Fantasy",
  "Fiction",
  "Graphic Novel",
  "Health",
  "Historical Fiction",
  "History",
  "Horror",
  "Humor",
  "LGBTQ+",
  "Literary Fiction",
  "Magic Realism",
  "Memoir",
  "Motivational",
  "Music",
  "Mystery",
  "Mythology",
  "Non-Fiction",
  "Paranormal",
  "Philosophy",
  "Poetry",
  "Politics",
  "Psychology",
  "Religion",
  "Romance",
  "Romantic Comedy",
  "Satire",
  "Science",
  "Science Fiction",
  "Self-Help",
  "Short Stories",
  "Spirituality",
  "Sports",
  "Supernatural",
  "Suspense",
  "Technology",
  "Thriller",
  "Travel",
  "True Crime",
  "War",
  "Western",
  "Women's Fiction",
  "Young Adult",
];

export default GENRES;
